# Server Configuration
server:
  port: 3010
  error:
    include-message: always

spring:
  web:
    resources:
      add-mappings: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false

---
# Postgress Configuration
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.235:5432/nDB?currentSchema=sb.wali.co
    username: numan
    password: 2204
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
